---
kind: pipeline
type: docker
name: verify
steps:
- name: install
  image: danlynn/ember-cli:4.2.0-node_16.14
  commands:
  - npm install
- name: lint
  image: danlynn/ember-cli:4.2.0-node_16.14
  commands:
  - npm run lint
- name: test
  image: danlynn/ember-cli:4.2.0-node_16.14
  commands:
  - npm run test:ember
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: npm-release
  image: plugins/npm
  settings:
    token:
      from_secret: npm_access_token
trigger:
  event:
    - tag

---

kind: secret
name: docker_username
data: cRILPiMnM6n7vPKLMd4cE4b67TYU/5IB+5nW6iXW3ZeKA4pc3vWdug==

---

kind: secret
name: docker_password
data: oLwclWhPPqNBeQqwfmEE8NaFskc5JpqqnKFQtPehWIGAxBu4qRQjpOA=

---
