matrix:
  scenario:
    - ember-lts-4.12
steps:
  - name: ${scenario}
    image: danlynn/ember-cli:6.2.1-node_22.14
    commands:
      - npx @embroider/try apply {$scenario}
      - npm install
      - npm test
    # TODO: remove this once the issue is fixed in @embroider/try: https://discord.com/channels/480462759797063690/1479134791558234244/1479135429943890065
    failure: ignore

when:
  event:
    - pull_request
