matrix:
  scenario:
    - ember-lts-3.28
    - ember-lts-4.8
steps:
  - name: ${scenario}
    image: danlynn/ember-cli:4.12.1
    commands:
      - npm ci
      - npx ember try:one ${scenario}
when:
  event:
    - pull_request