matrix:
  scenario:
    - ember-lts-4.12
steps:
  - name: ${scenario}
    image: danlynn/ember-cli:6.2.1-node_22.14
    commands:
      - npm ci
      - npx ember try:one ${scenario}
when:
  event:
    - pull_request
