steps:
  install:
    image: danlynn/ember-cli:6.2.1-node_22.14
    commands:
      - npm ci
  lint-js:
    image: danlynn/ember-cli:6.2.1-node_22.14
    group: check
    commands:
      - npm run lint:js
  lint-hbs:
    image: danlynn/ember-cli:6.2.1-node_22.14
    group: check
    commands:
      - npm run lint:hbs
  test:
    image: danlynn/ember-cli:6.2.1-node_22.14
    group: check
    commands:
      - npm run test:ember
when:
  event:
    - pull_request
